import express, { NextFunction, Request, Response, Router } from 'express';
import auth from './auth';
import * as m from '../controllers/matrimonyController';
import * as k from '../controllers/kundliController';
import * as pay from '../controllers/paymentController';
import * as photo from '../controllers/photoController';
import * as ai from '../controllers/aiController';
import * as safety from '../controllers/safetyController';
import { requireAuth, requireRole } from '../middleware/auth';
import * as verify from '../controllers/verificationController';
import * as adminCtl from '../controllers/adminController';
import * as account from '../controllers/accountController';

const w = (fn: (req: Request, res: Response) => Promise<unknown>) => (req: Request, res: Response, next: NextFunction) => fn(req, res).catch(next);
const api = Router();
api.get('/health', (_req, res) => res.json({ success: true, data: { status: 'ok', service: 'kulbandhan-api', time: new Date().toISOString() } }));
api.use('/auth', auth);

// Razorpay needs the raw request body for signature verification, ahead of json parsing.
api.post('/payments/webhook', express.raw({ type: 'application/json' }), (req, _res, next) => { (req as any).rawBody = req.body.toString('utf8'); req.body = JSON.parse((req as any).rawBody || '{}'); next(); }, w(pay.razorpayWebhook));

api.use(requireAuth);
api.delete('/account/me', w(account.deleteMine));
api.get('/profiles/me', w(m.getMine));
api.put('/profiles/me', w(m.saveMine));
api.patch('/profiles/me/visibility', w(m.setVisibility));
api.get('/profiles/:userId', w(m.viewProfile));
api.get('/discover', w(m.discover));
api.post('/interests', w(m.sendInterest));
api.get('/interests', w(m.listInterests));
api.post('/interests/:id/respond', w(m.respond));
api.get('/matches', w(m.listMatches));
api.get('/chat/:matchId/messages', w(m.getMessages));
api.post('/chat/:matchId/messages', w(m.sendMessage));
api.get('/kundli/me', w(k.getMyKundli));
api.post('/kundli/generate', w(k.generateKundli));
api.delete('/kundli/me/birth-details', w(k.deleteMyBirthDetails));
api.get('/kundli/me/divisional/:chartCode', w(k.getDivisionalChart));
api.get('/compatibility/:userId', w(k.compatibility));
api.get('/payments/status', w(pay.myStatus));
api.post('/payments/orders', w(pay.createOrder));
api.post('/payments/verify', w(pay.verifyPayment));
api.post('/payments/dev-confirm', w(pay.devConfirm));
api.post('/photos', w(photo.upload));
api.get('/photos/me', w(photo.listMine));
api.delete('/photos/:id', w(photo.remove));
api.patch('/photos/:id/visibility', w(photo.setVisibility));
api.get('/photos/user/:userId', w(photo.photosOf));
api.post('/photos/user/:userId/request-access', w(photo.requestAccess));
api.post('/photo-requests/:id/respond', w(photo.respondAccess));
api.post('/ai/search', w(ai.search));
api.get('/ai/match-explanation/:userId', w(ai.matchExplanation));
api.post('/ai/profile-assist', w(ai.profileAssist));
api.post('/reports', w(safety.createReport));
api.post('/blocks', w(safety.createBlock));
api.delete('/blocks/:userId', w(safety.removeBlock));
api.get('/blocks', w(safety.listBlocks));
api.post('/verification/request', w(verify.requestVerification));
api.get('/verification/me', w(verify.myVerifications));

const admin = Router();
admin.use(requireRole('ADMIN', 'SUPER_ADMIN', 'MODERATOR'));
admin.get('/dashboard', w(adminCtl.dashboard));
admin.get('/reports', w(adminCtl.listReports));
admin.post('/reports/:id/action', w(adminCtl.actOnReport));
admin.get('/verifications', w(adminCtl.listVerifications));
admin.post('/verifications/:id/review', w(adminCtl.reviewVerification));
admin.get('/users', w(adminCtl.listUsers));
admin.post('/users/:userId/moderation', requireRole('ADMIN', 'SUPER_ADMIN'), w(adminCtl.setModerationState));
admin.get('/audit-logs', requireRole('ADMIN', 'SUPER_ADMIN'), w(adminCtl.auditLogs));
api.use('/admin', admin);
export default api;
